{% set name = "json-schema-for-humans" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/json_schema_for_humans-{{ version }}.tar.gz
  sha256: 3e32701a7499eabb8585a3b9faf029aad94bf1c99b02bd54372d7a9b4696bb32
  patches:
    # https://github.com/coveooss/json-schema-for-humans/pull/242
    - 0001-dev-dependencies.patch

build:
  entry_points:
    - generate-schema-doc = json_schema_for_humans.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - click >=8.0.1,<9.0.0
    - dataclasses-json >=0.5.6,<0.6.0
    - htmlmin >=0.1.12,<0.2.0
    - jinja2 >3
    - markdown2 >=2.4.1,<3.0.0
    - pygments >=2.10.0,<3.0.0
    - pytz
    - pyyaml >=5.4.1,<7
    - requests >=2.31.0,<3.0.0
    - markupsafe >=2.0.0,<3.0.0

test:
  imports:
    - json_schema_for_humans
  commands:
    - pip check
    - generate-schema-doc --help
  requires:
    - pip

about:
  home: https://github.com/coveooss/json-schema-for-humans
  summary: Generate static HTML documentation from JSON schemas
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - pavelzw
