{% set name = "json-schema-for-humans" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/json_schema_for_humans-{{ version }}.tar.gz
  sha256: 5156c37d01adc1f9d755e42ce15d92860182ffa384dbaf62193c015eaa7f9986

build:
  entry_points:
    - generate-schema-doc = json_schema_for_humans.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - click >=8.0.1,<9.0.0
    - dataclasses-json >=0.6.7,<0.7.0
    - htmlmin2 >=0.1.13,<0.2.0
    - jinja2 >3
    - markdown2 >=2.5.0,<3.0.0
    - pygments >=2.18.0,<3.0.0
    - pytz
    - pyyaml >=6.0.2,<7
    - requests >=2.32.3,<3.0.0
    - markupsafe >=2.1.5,<3.0.0

test:
  imports:
    - json_schema_for_humans
  commands:
    - pip check
    - generate-schema-doc --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/coveooss/json-schema-for-humans
  summary: Generate static HTML documentation from JSON schemas
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - pavelzw
